name: Publish Release

on:
  workflow_dispatch:
      inputs:
        modrinth:
          description: 'Upload to Modrinth'
          required: true
          type: boolean
        curseforge:
          description: 'Upload to CurseForge'
          required: true
          type: boolean
        gh-releases:
          description: 'Upload to GH Releases'
          required: true
          type: boolean


permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get mod version
        id: version
        run: |
             VERSION=$(sed -n 's/^mod_version[[:space:]]*=[[:space:]]*//p' gradle.properties)
             echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build

      - name: Upload to Modrinth
        if: ${{ inputs.modrinth }}
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: n0AbAYWj
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          files: build/libs/*.jar

          name: 'Create: IDLX ${{ steps.version.outputs.version }} for Minecraft 1.21.1 & Create 6.0.X'
          version: 'mc1.21.1-${{ steps.version.outputs.version }}'
          version-type: release
          changelog-file: RELEASE_NOTES.md

          loaders: neoforge
          game-versions: 1.21.1
          java: 21

      - name: Upload to CurseForge
        if: ${{ inputs.curseforge }}
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          curseforge-id: 1456715
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          files: build/libs/*.jar

          name: 'Create: IDLX ${{ steps.version.outputs.version }} for Minecraft 1.21.1 & Create 6.0.X'
          version: 'mc1.21.1-${{ steps.version.outputs.version }}'
          version-type: release
          changelog-file: RELEASE_NOTES.md

          loaders: neoforge
          game-versions: 1.21.1
          java: 21

      - name: Upload to GH Releases
        if: ${{ inputs.gh-releases }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: '${{ steps.version.outputs.version }}'
          name: 'mc1.21.1-${{ steps.version.outputs.version }}'
          files: build/libs/*.jar
          body_path: RELEASE_NOTES.md