name: Publish Release

on:
  workflow_dispatch:
      inputs:
        modrinth:
          description: 'Upload to Modrinth'
          required: true
          type: boolean
        curseforge:
          description: 'Upload to CurseForge'
          required: true
          type: boolean
        gh-releases:
          description: 'Upload to GH Releases'
          required: true
          type: boolean


permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get mod version
        id: version
        run: |
             MOD_VERSION=$(sed -n 's/^mod_version[[:space:]]*=[[:space:]]*//p' gradle.properties)
             MC_VERSION=$(sed -n 's/^minecraft_version[[:space:]]*=[[:space:]]*//p' gradle.properties)
             LOADER=$(sed -n 's/^loader[[:space:]]*=[[:space:]]*//p' gradle.properties)
             JAVA_VERSION=$(sed -n 's/^java_version[[:space:]]*=[[:space:]]*//p' gradle.properties)
             echo "mod_version=$MOD_VERSION" >> $GITHUB_OUTPUT
             echo "mc_version=$MC_VERSION" >> $GITHUB_OUTPUT
             echo "loader=$LOADER" >> $GITHUB_OUTPUT
             echo "java_version=$JAVA_VERSION" >> $GITHUB_OUTPUT

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ steps.version.outputs.java_version }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build

      - name: Upload to Modrinth
        if: ${{ inputs.modrinth }}
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: n0AbAYWj
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          files: build/libs/*.jar

          name: 'Create: IDLX ${{ steps.version.outputs.mod_version }} for Minecraft ${{ steps.version.outputs.mc_version }} & Create 6.0.X'
          version: 'mc${{ steps.version.outputs.mc_version }}-${{ steps.version.outputs.mod_version }}'
          version-type: release
          changelog-file: RELEASE_NOTES.md

          loaders: ${{ steps.version.outputs.loader }}
          game-versions: ${{ steps.version.outputs.mc_version }}
          java: ${{ steps.version.outputs.java_version }}

      - name: Upload to CurseForge
        if: ${{ inputs.curseforge }}
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          curseforge-id: 1456715
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          files: build/libs/*.jar

          name: 'Create: IDLX ${{ steps.version.outputs.mod_version }} for Minecraft ${{ steps.version.outputs.mc_version }} & Create 6.0.X'
          version: 'mc${{ steps.version.outputs.mc_version }}-${{ steps.version.outputs.mod_version }}'
          version-type: release
          changelog-file: RELEASE_NOTES.md

          loaders: ${{ steps.version.outputs.loader }}
          game-versions: ${{ steps.version.outputs.mc_version }}
          java: ${{ steps.version.outputs.java_version }}

      - name: Upload to GH Releases
        if: ${{ inputs.gh-releases }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: 'mc${{ steps.version.outputs.mc_version }}-${{ steps.version.outputs.mod_version }}'
          name: 'Create: IDLX ${{ steps.version.outputs.mod_version }} for mc${{ steps.version.outputs.mc_version }}'
          files: build/libs/*.jar
          body_path: RELEASE_NOTES.md